version: '3'
services:
  api:
    container_name: flask-container
    build: .
    entrypoint: python app.py
    env_file:
      - .env
    ports:
      - '5006:5000'
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6380:6379"